### ISSUE TITLE
0.1.7 and 0.1.8

### ISSUE THREAD

**Issue by 0323pin** [gfannes/molybdenum#1]
Hi,

I maintain a package for `molybdenum` on NetBSD. Just realized I've missad the last two releases as they were just tagged on crates.io and not on Github.

I'll fix this asap but, would it possible to have sync releases so this doesn't happen again?

TIA

**Comment by 0323pin** [comment]
Done, v0.1.8 has now been merged into the main repository.

https://mail-index.netbsd.org/pkgsrc-changes/2022/05/12/msg254360.html

**Comment by gfannes** [comment]
Sorry, I forgot. I added them.
Greetings, Geert.

Op do 12 mei 2022 om 18:00 schreef pin ***@***.***>:

**Comment by 0323pin** [comment]
Thanks :)

**Comment by 0323pin** [comment]
@gfannes Is 0.1.9 official or just a dev branch?
Cheers!

**Comment by gfannes** [comment]
I created the tag to make it an official release.
Greetings, Geert.

Op vr 9 sep. 2022 om 14:13 schreef pin ***@***.***>:
